version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./storage/app/public:/var/www/html/public/storage
      - ./.env:/var/www/html/.env
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      APP_URL: http://65.108.220.94
      DB_CONNECTION: mysql
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: daw
      DB_USERNAME: admin
      DB_PASSWORD: admin
    command: >
      sh -c "
        php artisan key:generate --force &&
        php artisan config:clear &&
        php artisan config:cache &&
        php artisan serve --host=0.0.0.0 --port=8000
      "     - "80:80"
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      DB_CONNECTION: mysql
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: daw
      DB_USERNAME: admin
      DB_PASSWORD: admin
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'daw'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql-db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: admin

volumes:
  mysqldata:
